username = "username"
password = "pw"
jira_url = "http://localhost:8080"
query = "assignee%3D%27philipp.baum%27+AND+resolution+%3D+Unresolved"
md_file_path = "/Users/phil/Notes/Arbeit/0 Meta/021 Jira Tasks.md"
